version: '3'

services:
  web:
    build: .
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
      - DEBUG=True
      - DATABASE_URL=sqlite:///stock.db
    volumes:
      - ./instance:/app/instance
    command: python web_app.py